name: CI

on: push
  branches:
    - 'test-github-action'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: build an android container
        runs:
          using: 'docker'
          image: 'Dockerfile'
          args:
            - "-v /var/run/docker.sock:/var/run/docker.sock --privileged"
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
