name: CI

on:
  push:
    branches:
      - 'test-github-action'
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: ../../gradle/wrapper
          arguments: assembleDebug appDistributionUploadDebug
        id: gradle
