name: CI

on:
  push:
    branches:
      - 'test-github-action'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - uses: ./
      - name: build an android container
        run:
          using: 'docker'
          image: 'Dockerfile'
          args:
            - "-v /var/run/docker.sock:/var/run/docker.sock --privileged"
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
